-- TaskBuddy schema — provider identity verification
-- Source of truth: backend/BACKEND_SCHEMA.md §17 (added alongside this migration).
--
-- "Provider portfolios, certifications, or document verification" was listed
-- under Out of Scope in the original spec. It is now in scope: the web admin
-- console has always had a Verification queue page, and it ran entirely on
-- mock data because no table existed. This backs backlog stories #9 (provider
-- submits ID + selfie) and #28 (admin review queue).
--
-- Documents live in the PRIVATE `verification-docs` Storage bucket. Rows store
-- object *paths*; admins read them through short-lived signed download URLs
-- generated by the API. Never expose these objects publicly — they are
-- government IDs.
--
-- Conventions mirror 0001–0007.

-- ===========================================================================
-- 1. Enums
-- ===========================================================================
create type verification_status as enum ('pending', 'approved', 'rejected');

-- Providers are notified when their submission is reviewed. Postgres allows
-- ALTER TYPE ... ADD VALUE inside a transaction, but the new value cannot be
-- *used* until this migration commits — nothing here inserts a notification,
-- so applying this file in one go is safe.
alter type notification_type add value if not exists 'verification_update';

-- ===========================================================================
-- 2. Submissions
-- ===========================================================================
create table provider_verifications (
    id               uuid primary key default gen_random_uuid(),
    provider_id      uuid not null references profiles (id) on delete cascade,
    id_document_path text not null,
    selfie_path      text not null,
    status           verification_status not null default 'pending',
    submitted_at     timestamptz not null default now(),
    reviewed_at      timestamptz,
    reviewed_by      uuid references profiles (id),
    rejection_reason text check (char_length(rejection_reason) <= 500),
    created_at       timestamptz not null default now(),
    updated_at       timestamptz not null default now()
);

-- A provider may resubmit after a rejection, but only one review can be open
-- at a time — this is what makes POST /verifications idempotent-ish.
create unique index uq_provider_verifications_one_pending
    on provider_verifications (provider_id)
 where status = 'pending';

-- The admin queue filters by status, newest first.
create index idx_provider_verifications_status
    on provider_verifications (status, submitted_at desc);

create trigger trg_provider_verifications_updated_at
    before update on provider_verifications
    for each row execute function set_updated_at();

-- ===========================================================================
-- 3. Verified badge
--
--    Informational only — applying to jobs is deliberately NOT gated on this.
--    Gating would lock out every provider who signed up before verification
--    existed. See backend/README.md.
-- ===========================================================================
alter table provider_profiles
    add column is_verified boolean not null default false;

comment on column provider_profiles.is_verified is
    'Set true when a provider_verifications row is approved. Badge only — not enforced.';

-- ===========================================================================
-- 4. Private storage bucket for the documents
-- ===========================================================================
insert into storage.buckets (id, name, public)
values ('verification-docs', 'verification-docs', false)
on conflict (id) do nothing;

-- ===========================================================================
-- 5. Row Level Security (defense-in-depth; API uses the service-role key)
-- ===========================================================================
alter table provider_verifications enable row level security;

create policy provider_verifications_own_read on provider_verifications
    for select using (provider_id = auth.uid());
