-- TaskBuddy schema — profile avatars + per-user settings
-- Source of truth: backend/BACKEND_SCHEMA.md §19.
--
-- Two gaps the mobile app documents in mobile/README.md ("What's Not Wired Yet"):
--
--   1. "Change Photo" does nothing and avatar_url is never sent. The column has
--      existed since 0001, but there was no Storage bucket the API would issue
--      an upload URL for, so a device had nowhere to put the image.
--   2. The Settings screen's toggles are local useState — nothing is persisted.
--
-- Conventions mirror 0001–0010.

-- ===========================================================================
-- 1. Avatar storage
--
--    Public, like `job-photos` (0007) and unlike `verification-docs` (0008):
--    an avatar is shown to the other party on every job card and chat header,
--    and signing each one would mean a round-trip per row.
--
--    Object paths are `<profile id>/<uuid>.<ext>`, generated by the API, so one
--    user cannot overwrite another's. No storage RLS policies are needed:
--    signed upload URLs carry their own token and the API reads with the
--    service key.
-- ===========================================================================
insert into storage.buckets (id, name, public)
values ('avatars', 'avatars', true)
on conflict (id) do nothing;

-- ===========================================================================
-- 2. User settings
--
--    One row per profile, created lazily by the API on first read rather than
--    by a trigger on `profiles`: the defaults live here in the DDL, so a user
--    who never opens the Settings screen needs no row at all.
--
--    Columns rather than a jsonb blob — every toggle is a fixed, known boolean
--    that the push scheduler and future email/SMS senders have to filter on,
--    and a column keeps that a cheap indexed predicate instead of a JSON probe.
-- ===========================================================================
create table if not exists user_settings (
    profile_id        uuid primary key references profiles (id) on delete cascade,

    -- Delivery channels. `push_enabled` is consulted by the notification push
    -- scheduler (0012); the email and SMS flags are stored now so the Settings
    -- screen round-trips honestly, but no transport reads them yet.
    push_enabled      boolean not null default true,
    email_enabled     boolean not null default true,
    sms_enabled       boolean not null default false,

    -- Whether the user agrees to share device location with the other party.
    location_sharing  boolean not null default true,

    -- Theme preference. Stored server-side so it survives a reinstall; the app
    -- is free to apply it before the first render from its own cache.
    dark_mode         boolean not null default false,

    created_at        timestamptz not null default now(),
    updated_at        timestamptz not null default now()
);

drop trigger if exists trg_user_settings_updated_at on user_settings;
create trigger trg_user_settings_updated_at
    before update on user_settings
    for each row execute function set_updated_at();

comment on table user_settings is
    'Per-user preferences. Rows are created on demand by GET /settings; a '
    'missing row means "all defaults", which is why every column is NOT NULL '
    'with a default.';

-- ===========================================================================
-- 3. Row Level Security (defense-in-depth; API uses service-role key)
-- ===========================================================================
alter table user_settings enable row level security;

drop policy if exists user_settings_owner_read on user_settings;
create policy user_settings_owner_read on user_settings
    for select using (profile_id = auth.uid());
