-- TaskBuddy — Google sign-in session handoff (BACKEND_SCHEMA.md §19)
--
-- The OAuth callback used to append the Supabase session to the app's deep
-- link (`taskbuddy://?access_token=…`). That made a single delivery of one URL
-- the only way a session could ever reach the app, and on Android it does not
-- reliably arrive: Chrome drops a 302 into an app scheme, and a development
-- build *restarts* on its own scheme, tearing down the JS context that was
-- waiting for it. Either way the tokens were gone for good and the user landed
-- back on the sign-in screen having authenticated successfully.
--
-- So the callback now parks the session here under a one-time code and sends
-- the app only that code. The app claims the session over HTTPS and can retry
-- until it succeeds — the deep link became an optimisation instead of the
-- delivery mechanism. Tokens also stop appearing in browser history and in the
-- interstitial page's URL.
--
-- Conventions mirror 0001-0032.

create table if not exists oauth_handoffs (
    -- sha256 of the code, never the code itself: a leaked backup of this table
    -- must not be a pile of usable sign-in credentials.
    code_hash   text primary key,
    session     jsonb       not null,
    created_at  timestamptz not null default now(),
    expires_at  timestamptz not null
);

comment on table oauth_handoffs is
    'One-time handoff of a Supabase session from the Google OAuth callback to '
    'the mobile app (BACKEND_SCHEMA.md §19). Rows live ~5 minutes and are '
    'deleted the moment they are claimed.';

comment on column oauth_handoffs.code_hash is
    'sha256(handoff id) in hex. The id is generated by the app, travels in the '
    'signed OAuth state, and is returned to the app on the deep link.';

comment on column oauth_handoffs.session is
    'access_token, refresh_token and expires_at, exactly as POST /auth/login '
    'returns them.';

-- Claiming deletes the row, so single use needs no consumed_at flag — the
-- delete either matched a row or it did not. This index serves the sweep of
-- rows nobody ever claimed (an abandoned sign-in), which AuthService runs
-- opportunistically on each claim.
create index if not exists idx_oauth_handoffs_expires_at
    on oauth_handoffs (expires_at);

-- Defence in depth, same shape as provider_payout_accounts (0028): the API
-- only ever touches this table with the service-role key, which bypasses RLS.
-- Enabling it with no policies means a user-scoped key reaching Postgres
-- directly reads nothing — and this table holds live session tokens, so that
-- matters more here than anywhere else in the schema.
alter table oauth_handoffs enable row level security;
